version: '2'

services:
  urlshortner-mysql:
    container_name: urlshortner-mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    restart: always

  urlshortner-app:
    container_name: urlshortner-app
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - urlshortner-mysql
    ports:
      - "8181:8181"
    restart: always
